# Generated by Django 4.2 on 2024-08-19 18:58

import aziende.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stabilimenti',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descrizione', models.CharField(help_text='Stabilimento', max_length=250)),
                ('immagine', models.ImageField(blank=True, default='aziende/img/aziende.png', help_text='Caricare un Immagine (opzionale)', null=True, upload_to=aziende.models.aziende_directory_path)),
                ('email', models.EmailField(blank=True, max_length=100, null=True, unique=True)),
                ('creato', models.DateTimeField(auto_now_add=True)),
                ('aggiornato', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Stabilimento',
                'verbose_name_plural': 'Stabilimenti',
            },
        ),
        migrations.CreateModel(
            name='Ute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descrizione', models.CharField(help_text='Ute da creare  Es: Ute1', max_length=200)),
                ('creato', models.DateTimeField(auto_now_add=True)),
                ('aggiornato', models.DateTimeField(auto_now=True)),
                ('id_stabilimento', models.ForeignKey(help_text='Stabilimento', on_delete=django.db.models.deletion.CASCADE, to='aziende.stabilimenti', verbose_name='Stabilimento')),
            ],
            options={
                'verbose_name': 'Ute',
                'verbose_name_plural': 'Ute',
            },
        ),
        migrations.CreateModel(
            name='Reparti',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descrizione', models.CharField(help_text='Reparto da creare', max_length=200)),
                ('creato', models.DateTimeField(auto_now_add=True)),
                ('aggiornato', models.DateTimeField(auto_now=True)),
                ('id_ute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aziende.ute', verbose_name='Ute')),
            ],
            options={
                'verbose_name': 'Reparto',
                'verbose_name_plural': 'Reparti',
            },
        ),
    ]
