# Generated by Django 4.2 on 2024-08-19 18:58

import assistenza.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_utils.choices


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('checklist', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Aziende',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descrizione', models.CharField(help_text='Stabilimento', max_length=250)),
                ('immagine', models.ImageField(blank=True, default='assistenza/img/assistenza.jpeg', help_text='Caricare un Immagine (opzionale)', null=True, upload_to=assistenza.models.assistenza_directory_path)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('creato', models.DateTimeField(auto_now_add=True)),
                ('aggiornato', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Azienda Assistenza',
                'verbose_name_plural': 'Aziende Assistenza',
            },
        ),
        migrations.CreateModel(
            name='Interventi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intervento', models.TextField(help_text='Specificare gli interventi effettuati', verbose_name='Intervento')),
                ('ore', models.PositiveIntegerField(default=0, help_text='Lettura ore di lavoro Mezzo', verbose_name='Ore')),
                ('evasa', models.BooleanField(choices=[(True, django_utils.choices.Choice(True, 'SI')), (False, django_utils.choices.Choice(False, 'Salva e riprendi più tardi'))], default=False)),
                ('creato', models.DateTimeField(auto_now_add=True)),
                ('aggiornato', models.DateTimeField(auto_now=True)),
                ('id_controllo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checklist.controlli', verbose_name='Controllo')),
                ('modificato', models.ForeignKey(help_text='Operatore', on_delete=django.db.models.deletion.CASCADE, related_name='operatore', to=settings.AUTH_USER_MODEL, verbose_name='Operatore')),
                ('operatore', models.ForeignKey(help_text='Operatore', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Operatore')),
            ],
            options={
                'verbose_name': 'Intevento',
                'verbose_name_plural': 'Interventi',
                'ordering': ['-creato'],
            },
        ),
    ]
