# Generated by Django 4.2 on 2024-08-08 07:56

import assistenza.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('flotta', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Aziende',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descrizione', models.CharField(help_text='Stabilimento', max_length=250)),
                ('immagine', models.ImageField(blank=True, default='assistenza/img/assistenza.jpeg', help_text='Caricare un Immagine (opzionale)', null=True, upload_to=assistenza.models.assistenza_directory_path)),
                ('telefono', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None, unique=True)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('creato', models.DateTimeField(auto_now_add=True)),
                ('aggiornato', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Azienda Assistenza',
                'verbose_name_plural': 'Aziende Assistenza',
            },
        ),
        migrations.CreateModel(
            name='OreLavoroMezzi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ore', models.PositiveIntegerField(default=0, help_text='Lettura ore di lavoro Mezzo', verbose_name='Ore')),
            ],
            options={
                'verbose_name': 'Ore Lavoro Mezzo',
                'verbose_name_plural': 'Ore Lavoro Mezzi',
            },
        ),
        migrations.CreateModel(
            name='ManutenzioneStraordinaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creato', models.DateTimeField(auto_now_add=True)),
                ('aggiornato', models.DateTimeField(auto_now=True)),
                ('id_azienda', models.ForeignKey(help_text='Azienda chec ha effettuato intervento', on_delete=django.db.models.deletion.CASCADE, to='assistenza.aziende', verbose_name='Azienda')),
                ('id_mezzo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flotta.mezzi', verbose_name='Mezzo')),
                ('id_operatore', models.ForeignKey(help_text='Operatore che ha effettuato la mautenzione ordinaria', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Operatore')),
            ],
            options={
                'verbose_name': 'Manutenzione Straordinaria',
                'verbose_name_plural': 'Manutenzione Straordinaria',
                'ordering': ['-creato'],
            },
        ),
        migrations.CreateModel(
            name='ManutenzioneOrdinaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creato', models.DateTimeField(auto_now_add=True)),
                ('aggiornato', models.DateTimeField(auto_now=True)),
                ('id_azienda', models.ForeignKey(help_text='Azienda chec ha effettuato intervento', on_delete=django.db.models.deletion.CASCADE, to='assistenza.aziende', verbose_name='Azienda')),
                ('id_mezzo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flotta.mezzi', verbose_name='Mezzo')),
                ('id_operatore', models.ForeignKey(help_text='Operatore che ha effettuato la mautenzione ordinaria', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Operatore')),
                ('ore_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assistenza.orelavoromezzi', verbose_name='Ore')),
            ],
            options={
                'verbose_name': 'Manutenzione Ordinaria',
                'verbose_name_plural': 'Manutenzione Ordinaria',
                'ordering': ['-creato'],
            },
        ),
        migrations.CreateModel(
            name='InterventiStraordinari',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intervento', models.TextField(help_text='Specificare gli interventi effettuati', verbose_name='Intervento')),
                ('id_manutenzione', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assistenza.manutenzionestraordinaria', verbose_name='Manutenzione Straordinaria')),
            ],
            options={
                'verbose_name': 'Intevento Straordinario',
                'verbose_name_plural': 'Interventi Straordinari',
            },
        ),
        migrations.CreateModel(
            name='InterventiOrdinari',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intervento', models.TextField(help_text='Specificare gli interventi effettuati', verbose_name='Intervento')),
                ('id_manutenzione', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assistenza.manutenzioneordinaria', verbose_name='Manutenzione Ordinaria')),
            ],
            options={
                'verbose_name': 'Intevento Ordinario',
                'verbose_name_plural': 'Interventi Ordinari',
            },
        ),
    ]
