# Generated by Django 4.2 on 2024-08-25 18:02

from django.db import migrations, models
import django_utils.choices


class Migration(migrations.Migration):

    dependencies = [
        ('assistenza', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interventi',
            name='evasa',
            field=models.BooleanField(choices=[(True, django_utils.choices.Choice(True, 'Si')), (False, django_utils.choices.Choice(False, 'Salva e riprendi più tardi'))], default=False),
        ),
    ]
