# Generated by Django 4.2 on 2024-08-12 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistenza', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manutenzioneordinaria',
            name='ore_id',
        ),
        migrations.AddField(
            model_name='manutenzioneordinaria',
            name='ore',
            field=models.PositiveIntegerField(default=0, help_text='Lettura ore di lavoro Mezzo', verbose_name='Ore'),
        ),
        migrations.DeleteModel(
            name='OreLavoroMezzi',
        ),
    ]
