# Generated by Django 4.2 on 2024-08-12 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assistenza', '0002_remove_manutenzioneordinaria_ore_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='manutenzioneordinaria',
            old_name='id_operatore',
            new_name='operatore',
        ),
        migrations.RenameField(
            model_name='manutenzionestraordinaria',
            old_name='id_operatore',
            new_name='operatore',
        ),
    ]
