# Generated by Django 4.2 on 2024-08-12 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistenza', '0003_rename_id_operatore_manutenzioneordinaria_operatore_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manutenzioneordinaria',
            name='ore',
        ),
        migrations.AddField(
            model_name='interventiordinari',
            name='ore',
            field=models.PositiveIntegerField(default=0, help_text='Lettura ore di lavoro Mezzo', verbose_name='Ore'),
        ),
    ]
