# Generated by Django 4.2 on 2024-08-13 20:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_utils.choices


class Migration(migrations.Migration):

    dependencies = [
        ('flotta', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('assistenza', '0004_remove_manutenzioneordinaria_ore_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interventi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creato', models.DateTimeField(auto_now_add=True)),
                ('aggiornato', models.DateTimeField(auto_now=True)),
                ('evasa', models.BooleanField(choices=[(True, django_utils.choices.Choice(True, 'SI')), (False, django_utils.choices.Choice(False, 'NO'))], default=False)),
                ('id_azienda', models.ForeignKey(help_text='Azienda chec ha effettuato intervento', on_delete=django.db.models.deletion.CASCADE, to='assistenza.aziende', verbose_name='Azienda')),
                ('id_mezzo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flotta.mezzi', verbose_name='Mezzo')),
                ('operatore', models.ForeignKey(help_text='Operatore che ha effettuato la mautenzione ordinaria', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Operatore')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
