# Generated by Django 4.2 on 2024-08-13 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistenza', '0005_interventi'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='interventi',
            options={'verbose_name': 'Intevento', 'verbose_name_plural': 'Interventi'},
        ),
        migrations.AddField(
            model_name='interventi',
            name='intervento',
            field=models.TextField(default=1, help_text='Specificare gli interventi effettuati', verbose_name='Intervento'),
            preserve_default=False,
        ),
    ]
