# Generated by Django 4.2 on 2024-08-14 13:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('assistenza', '0006_alter_interventi_options_interventi_intervento'),
    ]

    operations = [
        migrations.AddField(
            model_name='interventi',
            name='ore',
            field=models.PositiveIntegerField(default=1, help_text='Lettura ore di lavoro Mezzo', verbose_name='Ore'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='interventi',
            name='id_azienda',
            field=models.ForeignKey(help_text='Azienda', on_delete=django.db.models.deletion.CASCADE, to='assistenza.aziende', verbose_name='Azienda'),
        ),
        migrations.AlterField(
            model_name='interventi',
            name='operatore',
            field=models.ForeignKey(help_text='Operatore', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Operatore'),
        ),
        migrations.AlterField(
            model_name='manutenzioneordinaria',
            name='id_azienda',
            field=models.ForeignKey(help_text='Azienda', on_delete=django.db.models.deletion.CASCADE, to='assistenza.aziende', verbose_name='Azienda'),
        ),
        migrations.AlterField(
            model_name='manutenzioneordinaria',
            name='operatore',
            field=models.ForeignKey(help_text='Operatore', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Operatore'),
        ),
        migrations.AlterField(
            model_name='manutenzionestraordinaria',
            name='id_azienda',
            field=models.ForeignKey(help_text='Azienda', on_delete=django.db.models.deletion.CASCADE, to='assistenza.aziende', verbose_name='Azienda'),
        ),
        migrations.AlterField(
            model_name='manutenzionestraordinaria',
            name='operatore',
            field=models.ForeignKey(help_text='Operatore', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Operatore'),
        ),
    ]
