# Generated by Django 4.2 on 2024-08-14 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistenza', '0007_interventi_ore_alter_interventi_id_azienda_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interventi',
            name='ore',
            field=models.PositiveIntegerField(default=0, help_text='Lettura ore di lavoro Mezzo', verbose_name='Ore'),
        ),
    ]
