# Generated by Django 4.2 on 2024-08-19 18:58

import accounts.models
from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('aziende', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('first_name', models.CharField(max_length=100, verbose_name='Nome')),
                ('last_name', models.CharField(max_length=100, verbose_name='Cognome')),
                ('squadra', models.PositiveSmallIntegerField(choices=[(1, 'SQUADRA A'), (2, 'SQUADRA B'), (3, 'SQUADRA C'), (4, 'BITURNISTA'), (5, 'ASSISTENZA'), (6, 'ADMIN')], default=6, verbose_name='Squadra')),
                ('role', models.CharField(choices=[('ADMIN', 'ADMIN'), ('OPERATORE', 'OPERATORE'), ('RESPONSABILE', 'RESPONSABILE'), ('ASSISTENZA', 'ASSISTENZA')], max_length=50, verbose_name='Ruolo')),
                ('avatar', models.ImageField(blank=True, default='avatar/img/operatore/operatore.png', null=True, upload_to=accounts.models.user_directory_path)),
                ('last_login', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Ultimo Accesso')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creato')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Aggiornato')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='AssistenzaProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Profilo Operatore Manutenzione',
                'verbose_name_plural': 'Profilo Operatore Manutenzione',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('azienda', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='aziende.stabilimenti', verbose_name='Stabilimento')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Operatore')),
            ],
            options={
                'verbose_name': 'Profilo Utente',
                'verbose_name_plural': 'Profili Utenti',
            },
        ),
    ]
