# Generated by Django 4.2 on 2024-08-08 07:56

import accounts.models
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('first_name', models.CharField(max_length=100, verbose_name='Nome')),
                ('last_name', models.CharField(max_length=100, verbose_name='Cognome')),
                ('squadra', models.PositiveSmallIntegerField(choices=[(1, 'SQUADRA A'), (2, 'SQUADRA B'), (3, 'SQUADRA C'), (4, 'BITURNISTA')], default=1, verbose_name='Squadra')),
                ('role', models.CharField(choices=[('ADMIN', 'ADMIN'), ('OPERATORE', 'OPERATORE'), ('RESPONSABILE', 'RESPONSABILE'), ('ASSISTENZA', 'ASSISTENZA')], max_length=50, verbose_name='Ruolo')),
                ('avatar', models.ImageField(blank=True, default='avatar/img/operatore/operatore.png', null=True, upload_to=accounts.models.user_directory_path)),
                ('last_login', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Ultimo Accesso')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creato')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Aggiornato')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
            ],
            options={
                'verbose_name': 'Admin',
                'verbose_name_plural': 'Admin',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('accounts.user',),
        ),
        migrations.CreateModel(
            name='Assistenza',
            fields=[
            ],
            options={
                'verbose_name': 'Assistenza',
                'verbose_name_plural': 'Assistenza',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('accounts.user',),
        ),
        migrations.CreateModel(
            name='Operatore',
            fields=[
            ],
            options={
                'verbose_name': 'Operatore',
                'verbose_name_plural': 'Operatori',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('accounts.user',),
        ),
        migrations.CreateModel(
            name='Responsabile',
            fields=[
            ],
            options={
                'verbose_name': 'Responsabile',
                'verbose_name_plural': 'Responsabili',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('accounts.user',),
        ),
    ]
