# Generated by Django 4.2 on 2024-08-09 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='squadra',
            field=models.PositiveSmallIntegerField(choices=[(1, 'SQUADRA A'), (2, 'SQUADRA B'), (3, 'SQUADRA C'), (4, 'BITURNISTA'), (5, 'ASSISTENZA')], default=1, verbose_name='Squadra'),
        ),
    ]
