# Generated by Django 4.2 on 2024-08-19 18:58

from django.db import migrations, models
import django.db.models.deletion
import flotta.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('aziende', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descrizione', models.CharField(help_text='Inserire la Categoria di Mezzi', max_length=100, verbose_name='Descrizione')),
                ('immagine', models.ImageField(blank=True, default='categoria/img/categorie.jpeg', help_text='Caricare un Immagine (opzionale)', null=True, upload_to=flotta.models.categoria_directory_path)),
                ('creato', models.DateTimeField(auto_now_add=True)),
                ('aggiornato', models.DateTimeField(auto_now=True)),
                ('id_reparto', models.ForeignKey(help_text='Reparto', on_delete=django.db.models.deletion.CASCADE, to='aziende.reparti', verbose_name='Reparto')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorie',
            },
        ),
        migrations.CreateModel(
            name='Mezzi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interno', models.CharField(help_text='Inserire un Identificativo univoco, Es. CR1', max_length=5, unique=True, verbose_name='Interno del Mezzo')),
                ('descrizione', models.CharField(help_text='Descrizione del Mezzo', max_length=100, verbose_name='Descrizione')),
                ('matricola', models.CharField(help_text='Inserire numero matricola ( presente sul mezzo)', max_length=20, unique=True, verbose_name='Matricola Mezzo')),
                ('immagine', models.ImageField(blank=True, default='mezzi/img/carrello.jpg', help_text='Caricare un Immagine (opzionale)', null=True, upload_to=flotta.models.mezzi_directory_path)),
                ('creato', models.DateTimeField(auto_now_add=True)),
                ('aggiornato', models.DateTimeField(auto_now=True)),
                ('id_categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flotta.categorie', verbose_name='Categoria')),
            ],
            options={
                'verbose_name': 'Mezzo',
                'verbose_name_plural': 'Mezzi',
            },
        ),
    ]
