# Generated by Django 4.2 on 2024-08-08 08:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_utils.choices


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('flotta', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turno', models.CharField(choices=[('PRIMO', 'Primo'), ('SECONDO', 'Secondo'), ('TERZO', 'Terzo'), ('CENTRALE', 'Centrale')], default='PRIMO', max_length=100)),
                ('creato', models.DateTimeField(auto_now_add=True)),
                ('aggiornato', models.DateTimeField(auto_now=True)),
                ('id_mezzo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flotta.mezzi', verbose_name='Mezzo')),
                ('operatore', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Operatore')),
            ],
            options={
                'verbose_name': 'Checklist',
                'verbose_name_plural': 'Checklists',
                'ordering': ['-creato'],
            },
        ),
        migrations.CreateModel(
            name='Controlli',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('controllo_luci_lampeggiante', models.CharField(choices=[('OK', django_utils.choices.Choice('OK', 'OK')), ('KO', django_utils.choices.Choice('KO', 'KO'))], default='OK', help_text='CONTROLLO LUCI LAMPEGGIANTE', max_length=2, verbose_name='Controllo luci lampeggiante')),
                ('controllo_avvisatori', models.CharField(choices=[('OK', django_utils.choices.Choice('OK', 'OK')), ('KO', django_utils.choices.Choice('KO', 'KO'))], default='OK', help_text='CONTROLLO AVVISATORI ACUSTICI (MANUALE E RETROMARCIA)', max_length=2, verbose_name='Controllo avvisatori')),
                ('controllo_sollevamento', models.CharField(choices=[('OK', django_utils.choices.Choice('OK', 'OK')), ('KO', django_utils.choices.Choice('KO', 'KO'))], default='OK', help_text='CONTROLLO DISPOSITIVO SOLLEVAMENTO STERZO', max_length=2, verbose_name='Controllo sollevamento')),
                ('controllo_telaio', models.CharField(choices=[('OK', django_utils.choices.Choice('OK', 'OK')), ('KO', django_utils.choices.Choice('KO', 'KO'))], default='OK', help_text='ANOMALIE TELAIO (PORTE, VETRI, ecc.)', max_length=2, verbose_name='Controllo telaio')),
                ('controllo_batteria', models.CharField(choices=[('OK', django_utils.choices.Choice('OK', 'OK')), ('KO', django_utils.choices.Choice('KO', 'KO'))], default='OK', help_text='CONTROLLO FUNZIONALE BATTERIA (CARICA) RABOCCHI (SE NECESSARIO)', max_length=2, verbose_name='Controllo batteria')),
                ('controllo_forche', models.CharField(choices=[('OK', django_utils.choices.Choice('OK', 'OK')), ('KO', django_utils.choices.Choice('KO', 'KO'))], default='OK', help_text='CONTROLLO PRESENZA BLOCCO SICUREZZA USCITA FORCHE', max_length=2, verbose_name='Controllo forche')),
                ('sostituzione_batteria', models.CharField(choices=[('OK', django_utils.choices.Choice('OK', 'OK')), ('KO', django_utils.choices.Choice('KO', 'KO'))], default='OK', help_text='LA SOSTITUZIONE DELLA BATTERIA VIENE VISUALIZZATO SUL DISPLAY CIRCA 20%', max_length=2, verbose_name='Sostituzione Batteria')),
                ('anomalie', models.TextField(blank=True, null=True)),
                ('id_checklist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checklist.checklist', verbose_name='CheckList')),
            ],
            options={
                'verbose_name': 'Controllo',
                'verbose_name_plural': 'Controlli',
            },
        ),
    ]
