# Generated by Django 4.2 on 2024-08-19 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='controlli',
            options={'ordering': ['creato'], 'verbose_name': 'Controllo', 'verbose_name_plural': 'Controlli'},
        ),
    ]
