# Generated by Django 4.2 on 2024-08-09 18:03

from django.db import migrations, models
import django_utils.choices


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0006_alter_controlli_controllo_avvisatori_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controlli',
            name='controllo_avvisatori',
            field=models.CharField(choices=[('OK', django_utils.choices.Choice('OK', 'OK')), ('KO', django_utils.choices.Choice('KO', 'KO'))], default='OK', help_text='CONTROLLO AVVISATORI ACUSTICI (MANUALE E RETROMARCIA)', max_length=2, verbose_name='Controllo avvisatori'),
        ),
        migrations.AlterField(
            model_name='controlli',
            name='controllo_batteria',
            field=models.CharField(choices=[('OK', django_utils.choices.Choice('OK', 'OK')), ('KO', django_utils.choices.Choice('KO', 'KO'))], default='OK', help_text='CONTROLLO FUNZIONALE BATTERIA (CARICA) RABOCCHI (SE NECESSARIO)', max_length=2, verbose_name='Controllo batteria'),
        ),
        migrations.AlterField(
            model_name='controlli',
            name='controllo_forche',
            field=models.CharField(choices=[('OK', django_utils.choices.Choice('OK', 'OK')), ('KO', django_utils.choices.Choice('KO', 'KO'))], default='OK', help_text='CONTROLLO PRESENZA BLOCCO SICUREZZA USCITA FORCHE', max_length=2, verbose_name='Controllo forche'),
        ),
        migrations.AlterField(
            model_name='controlli',
            name='controllo_luci_lampeggiante',
            field=models.CharField(choices=[('OK', django_utils.choices.Choice('OK', 'OK')), ('KO', django_utils.choices.Choice('KO', 'KO'))], default='OK', help_text='CONTROLLO LUCI LAMPEGGIANTE', max_length=2, verbose_name='Controllo luci lampeggiante'),
        ),
        migrations.AlterField(
            model_name='controlli',
            name='controllo_sollevamento',
            field=models.CharField(choices=[('OK', django_utils.choices.Choice('OK', 'OK')), ('KO', django_utils.choices.Choice('KO', 'KO'))], default='OK', help_text='CONTROLLO DISPOSITIVO SOLLEVAMENTO STERZO', max_length=2, verbose_name='Controllo sollevamento'),
        ),
        migrations.AlterField(
            model_name='controlli',
            name='controllo_telaio',
            field=models.CharField(choices=[('OK', django_utils.choices.Choice('OK', 'OK')), ('KO', django_utils.choices.Choice('KO', 'KO'))], default='OK', help_text='ANOMALIE TELAIO (PORTE, VETRI, ecc.)', max_length=2, verbose_name='Controllo telaio'),
        ),
        migrations.AlterField(
            model_name='controlli',
            name='sostituzione_batteria',
            field=models.CharField(choices=[('OK', django_utils.choices.Choice('OK', 'OK')), ('KO', django_utils.choices.Choice('KO', 'KO'))], default='OK', help_text='LA SOSTITUZIONE DELLA BATTERIA VIENE VISUALIZZATO SUL DISPLAY CIRCA 20%', max_length=2, verbose_name='Sostituzione Batteria'),
        ),
    ]
