# Generated by Django 4.2 on 2024-08-09 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flotta', '0001_initial'),
        ('checklist', '0007_alter_controlli_controllo_avvisatori_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checklist',
            name='id_mezzo',
        ),
        migrations.AddField(
            model_name='controlli',
            name='id_mezzo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='flotta.mezzi', verbose_name='Mezzo'),
            preserve_default=False,
        ),
    ]
